title: Welcome to the ZOO
author: Idir
email: 300117444@monboreal.ca
description: > # this means to ignore newlines until "baseurl:"
 Salut tout le monde et bienvenue sur ma page 
Je vous souhaite un agreable moment.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
